sudo: false
language: node_js
matrix:
  include:
  - node_js: 6
  - node_js: 7
  - node_js: 8
  - node_js: 9
  - node_js: 10
  - node_js: "lts/*"
  allow_failures:

before_script:
  - npm install -g istanbul coveralls
  - npm install -g mocha
  - npm install -g codeclimate-test-reporter
  - npm install

after_success:
  - make test-cov

script:
  - npm test

addons:
  code_climate:
    repo_token:

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d51130aaea652dbc8f1
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false

cache:
  directories:
  - "node_modules"
